project:
  type: website
  output-dir: _site

keywords: relatividade geral

lang: pt

format:
  html:
    theme: flatly
    css: styles.css
    toc: false

website:
  title: "sprg"
  description: "sociedade portuguesa de relatividade e gravitação"
  image: /media/sprg_redlogo.png
  favicon: /media/sprg_redlogo.png
  site-url: https://sprg.web.ua.pt/
  navbar:
    logo: /media/sprg_redlogo.png
    #title: false
    left:
      #- href: index.qmd
      #  text: SPRG
      - href: estatutos.qmd
        text: Estatutos
      - href: noticias.qmd
        text: Notícias
      - href: divulgacao.qmd
        text: Divulgação
      - href: membros.qmd
        text: Membros
      - href: assembleias.qmd
        text: Assembleias Gerais
      - href: corpos.qmd
        text: Corpos Sociais
      - href: info.qmd
        text: Contactos
  page-footer:
    left: "Contacto: s.p.rel.grav@gmail.com"
    border: true
    background: light
