## Officers (Membros dos orgãos sociais), 2022-2023

<!--
### Direcção

|                | 
:----------------|:----------------
Presidente       | Filipe Mena
Vice-Presidente  | José Lemos
Tesoureiro       | Jorge Rocha


### Assembleia Geral

|                | 
:----------------|:-----------------
Presidente       | Carlos Herdeiro
1º Secretário    | Miguel Zilhão
2º Secretário    | Pedro Cunha


Fiscal único:              J. Costa
-->

### Direcção

#### Presidente
Filipe Mena

#### Vice-Presidente
José Lemos

#### Tesoureiro
Jorge Rocha


### Assembleia Geral

#### Presidente
Carlos Herdeiro

#### 1º Secretário
Miguel Zilhão

#### 2º Secretário
Pedro Cunha


### Fiscal único
João Costa


## Officers (Membros dos orgãos sociais), 2020-2021

#### President (Presidente da Direcção)
José Sande Lemos  
IST, Universidade de Lisboa

#### Vice President (Vice-Presidente da Direcção)
Carlos Herdeiro  
Universidade de Aveiro

#### Treasurer (Tesoureiro)
João Costa  
ISCTE, Instituto Universitário de Lisboa

#### Auditor (Fiscal Único)
Jorge Rocha  
ISCTE, Instituto Universitário de Lisboa



#### President of the General Assembley (Presidente da Assembleia Geral)
Filipe Mena  
IST, Universidade de Lisboa

#### First Secretary (1º Secretário)
Miguel Zilhão  
IST, Universidade de Lisboa

#### Second Secretary (2º Secretario)
Pedro Cunha  
Universidade de Aveiro




## Officers (Membros dos orgãos sociais), 2018-2019

#### President (Presidente da Direcção)
Carlos Herdeiro  
Universidade de Aveiro and IST, Universidade de Lisboa

#### Vice President (Vice-Presidente da Direcção)
José Natário  
IST, Universidade de Lisboa

#### Treasurer (Tesoureiro)
Vitor Cardoso  
IST, Universidade de Lisboa

#### Auditor (Fiscal Único)
Jorge Rocha  
ISCTE, Instituto Universitário de Lisboa

#### President of the General Assembley (Presidente da Assembleia Geral)
José Sande Lemos 
IST, Universidade de Lisboa


#### First Secretary (1º Secretário)
Filipe Mena  
Universidade do Minho

#### Second Secretary (2º Secretario)
João Costa  
ISCTE, Instituto Universitário de Lisboa


## Officers (Membros dos orgãos sociais), 2016-2017

#### President (Presidente da Direcção)
José Natário  
IST, Universidade de Lisboa

#### Vice President (Vice-Presidente da Direcção)
Carlos Herdeiro  
Universidade de Aveiro

#### Treasurer (Tesoureiro)
Vitor Cardoso  
IST, Universidade de Lisboa

#### Auditor (Fiscal Único)
Francisco Lobo  
FCUL, Universidade de Lisboa

#### President of the General Assembley (Presidente da Assembleia Geral)
José Sande Lemos  
IST, Universidade de Lisboa


#### First Secretary (1º Secretário)
Filipe Mena  
Universidade do Minho

#### Second Secretary (2º Secretario)
João Costa  
ISCTE, Instituto Universitário de Lisboa
