
A Sociedade Portuguesa de Relatividade e Gravitação (SPRG) foi fundada em 2014, tendo como principal objectivo unir toda a comunidade científica portuguesa a trabalhar nos vários aspectos de Relatividade Geral e Gravitação.


## Objectivos

A SPRG é uma associação privada sem fins lucrativos que tem como objetivo promover e desenvolver a investigação e a divulgação da Relatividade e da Gravitação, em particular:

1. Proporcionando um foro independente para a discussão de assuntos relacionados com estes temas.
2. Tomando posições públicas conjuntas em defesa dos seus fins estatutários.
3. Mantendo relações institucionais com outras sociedades cujos objetivos sejam semelhantes.
4. Promovendo atividades de investigação e de divulgação relacionadas com a Relatividade e a Gravitação, incluindo a organização de reuniões científicas, conferências e publicações.
5. Estimulando o trabalho de jovens investigadores através da atribuição de um prémio anual.
6. Apoiando o ensino e a formação de investigadores em todas as áreas da Relatividade e da Gravitação.
