
## Associados

1. José Sande Lemos  
Instituto Superior Técnico -- CENTRA

2. José Natário  
Instituto Superior Técnico -- CAMGSD

3. Carlos Herdeiro  
Universidade de Aveiro -- Gr@v/CIDMA

4. Vitor Cardoso  
Instituto Superior Técnico -- CENTRA

5. João Lopes Costa  
ISCTE-IUL -- CAMGSD

6. Filipe Mena  
Instituto Superior Técnico -- CAMGSD

7. Filipe Moura  
ISCTE-IUL

8. Jorge Rocha  
ISCTE-IUL -- CENTRA

9. Miguel Zilhão  
Universidade de Aveiro -- Gr@v/CIDMA

10. Pedro Cunha  
Universidade de Aveiro -- Gr@v/CIDMA

11. Afonso Coxito  
FCTUC

12. Aleksandar Mikovic  
Universidade Lusófona e GFMUL

13. Alex H. Blin  
U. Coimbra

14. Alexandre Pombo  
FZU

15. Ana Maria Mourão  
Instituto Superior Técnico -- CENTRA

16. Andrea Maselli  
GSSI

17. André Martins  
Instituto Superior Técnico -- CENTRA

18. Anne Franzen  
Instituto Superior Técnico -- CAMGSD

19. Antonio Amorim  
FCUL -- CENTRA

20. Artur Alho  
Instituto Superior Técnico -- CAMGSD

21. Björn Gohla  
GFM/UL

22. Caio Bezerra Macedo  
UFPA

23. Carlos Frajuca  
IFSP

24. David Hilditch  
Instituto Superior Técnico -- CENTRA

25. Térence Delsate  
University of Mons, Belgium

26. Diego Rubiera-Garcia  
Universidad Complutense Madrid

27. Diogo Pinto Leite de Bragança  
Stanford University

28. Emanuele Berti  
Johns Hopkins University

29. Eugen Radu  
Universidade de Aveiro -- Gr@v/CIDMA

30. Fethi Mubin Ramazanoglu  
KOC UNIVERSITY (ISTANBUL)

31. Filipe Costa  
Instituto Superior Técnico -- CAMGSD

32. Flávio de Sousa Coelho  
Universidade de Aveiro -- Gr@v/CIDMA

33. Francisco Miguel Batista Duque  
Instituto Superior Técnico -- CENTRA

34. Francisco Lobo  
FCUL -- IA

35. Gonzalo J. Olmo  
Universidad de Valencia

36. Gonçalo Martins Quinta  
Instituto Superior Técnico

37. Grigorios Panotopoulos  
Universidad de la Frontera

38. Guilherme Raposo  
Universidade de Aveiro -- Gr@v/CIDMA

39. Gustavo Salgado Enríquez  
Instituto de Investigación Avanzada

40. Hugo Ferreira  
Feedzai

41. Ilidio Lopes  
Instituto Superior Técnico -- CENTRA

42. Irene Brito  
Universidade do Minho -- CMUM

43. Isabel Suárez Fernández  
Universitat de les Illes Balears

44. Javier Rubio  
Universidad Complutense Madrid

45. Jay Armas  
University of Amsterdam

46. Joao Carlos Vieira Rodrigues  
Universidade de Coimbra

47. João Luís Rosa  
University of Gdansk

48. João Rosa  
Universidade de Coimbra -- CFisUC

49. João Alves  
Universidade do Minho

50. João Oliveira  
Universidade do Minho -- CMUM

51. João Faria Martins  
University of Leeds

52. Jorge Drumond Silva  
Instituto Superior Técnico -- CAMGSD

53. Jorge Filipe Mónico Delgado  
Universidade de Aveiro -- Gr@v/CIDMA

54. Jorge Lopes  
Instituto Superior Técnico -- CENTRA

55. José Diogo Simão  
FSU Jena

56. José Manuel Mourão  
Instituto Superior Técnico -- CAMGSD

57. José Pedro Mimoso  
FCUL -- IA

58. Juan Carlos Degollado  
UNAM

59. Justin Christopher Feng  
Instituto Superior Técnico -- CENTRA

60. Jéssica Gonçalves  
University of Southampton

61. Laura Bernard  
Observatoire de Paris -- LUTH

62. Leonel Queimada  
Instituto Superior Técnico -- CENTRA

63. Luis Crispino  
UFPA

64. Marco Sampaio  
Feedzai

65. M. Margarida Lima  
Universidade do Minho

66. M. Piedade Machado-Ramos  
Universidade do Minho -- CMUM

67. Marko Vojinovic  
Universidade de Lisboa -- GFM

68. Miguel Duarte  
Instituto Superior Técnico -- CENTRA

69. Miguel Ferreira  
Instituto Superior Técnico -- CENTRA

70. NADJA SIMÃO MAGALHÃES  
Universidade Federal de São Paulo

71. Nelson Nunes  
FCUL -- IA

72. Nico Sanchis-Gual  
Universitat de València

73. Nuno M. Santos  
Universidade de Aveiro -- Gr@v/CIDMA  
Instituto Superior Técnico -- CENTRA

74. Paolo Pani  
Sapienza U. of Rome

75. Paulo Crawford  
FCUL, Aposentado

76. Paulo Luz  
ISCTE-IUL

77. Pedro Augusto  
IA

78. Pedro F. C. Oliveira  
Instituto Superior Técnico

79. Pedro Girão  
Instituto Superior Técnico -- CAMGSD

80. Pheiroijam Suranjoy Singh  
Bodoland University

81. Ricardo Zambujal Ferreira  
IFAE, Barcelona

82. Richard Pires Brito  
Instituto Superior Técnico -- CENTRA

83. Rita Teixeira da Costa  
Universidade de Cambridge

84. Robertus Potting  
Universidade do Algarve -- CENTRA

85. Rodrigo Vicente  
IFAE, Barcelona

86. Rui André  
Instituto Superior Técnico

87. Sante Carloni  
Università di Genova

88. Slobodeanu Radu  
University of Bucharest

89. Sofia Freitas  
Instituto Superior Técnico -- CENTRA

90. Suresh Nampuri  
CAMGSD-IST

91. Viktor G. Czinner  
Instituto Superior Técnico -- CENTRA

92. Vincenzo Vitagliano  
Università di Genova

93. Yasser Omar  
Instituto Superior Técnico -- Physics of Information Group, Instituto de Telecomunicações

94. Tiago Vasques Fernandes  
Instituto Superior Técnico -- CENTRA

95. Tomás Sousa  
University of Cambridge

96. Pedro Fernandes  
CP3-Origins, University of Southern Denmark

97. João Sieiro dos Santos  
Instituto Superior Técnico -- CENTRA

98. Hannes Rüter  
Instituto Superior Técnico -- CENTRA

99. Filip Hejda  
Instituto Superior Técnico -- CENTRA

100. Antonia Micol Frassino  
ICC, University of Barcelona & University of Alcalá
